plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.12-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.115' apply false
    id 'com.modrinth.minotaur' version '2.8.5' apply(false)
    id 'net.darkhax.curseforgegradle' version '1.0.11'

}