# Project
version=17.0.0
releasetype=release
changelog=update to 1.21.11
group=subaraki.paintings
java_version=21
mod_name=Paintings ++
mod_author=Subaraki
mod_id=paintings
license=MIT
displayURL=https://www.curseforge.com/minecraft/mc-mods/paintings
credits=David Goldman : the original Painting Selection Gui. Gigaherz for advice on networking. Darkhax and Jared for Multiloader
description=Add more paintings to your game and select them with the integrated interface.
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)
# NeoForge
neoforge_version=21.11.17-beta
neoforge_loader_version_range=[4,)
neo_form_version=1.21.11-20251209.172050

# Fabric
fabric_version=0.140.2+1.21.11
fabric_loader_version=0.18.4
parchment_minecraft=1.21.10
parchment_version=2025.10.12
cloth_config_version=21.11.153
mod_menu_version=17.0.0-beta.1
transparent=
ash_api=
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# publishing
modrinth_project=oQaAgvJv
cf_project=630726