package com.mcf.davidee.guilib;

import java.util.Arrays;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "guilib", name = "GUI Library", version = "$version")
public class GuiLibrary {

	
	@EventHandler 
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Davidee", "Subaraki  " });
		modMeta.autogenerated = false;
		modMeta.credits = "Davidee , original author. updated by Subaraki since 1.11";
		modMeta.description = "A small library for creating minecraft GUIs.";
		modMeta.url = "https://minecraft.curseforge.com/projects/painting-selection-gui-revamped";
	}
	
}
