plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'net.darkhax.curseforgegradle' version '1.0.11'
    id 'com.modrinth.minotaur'
}

repositories {
    mavenCentral()
    maven { url "https://jm.gserv.me/repository/maven-public/" }
    maven {
        name = 'Curse Maven'
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
}
dependencies {
//    runtimeOnly("curse.maven:transparent-377582:${transparent}")
//    runtimeOnly("curse.maven:ash-api-838498:${ash_api}")
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = findProperty('cf_api_token')

    // The main file to upload
    def mainFile = upload(cf_project, file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar"))
    mainFile.displayName = "${mod_name}-neo-${minecraft_version}-${version}"
    mainFile.releaseType = "${releasetype}"
    mainFile.changelog = "${changelog}"
    mainFile.changelogType = 'markdown'
    mainFile.addRequirement('transparent')
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addGameVersion("neoforge")
}

modrinth {
    token.set(project.findProperty('modrinth_api_token'))
    projectId.set(modrinth_project)
    changelog = "${changelog}"
    versionName.set("${mod_name}-NeoForge-${minecraft_version}-$version")
    versionType.set("${releasetype}")
    uploadFile.set(tasks.jar)
    dependencies {
        required.project("cloth-config")
        required.project("transparent")
    }
    loaders = ["neoforge"]
    gameVersions = ["${minecraft_version}"]
}

