package subaraki.paintings.mod;

import java.util.Collections;

import org.apache.logging.log4j.Logger;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import subaraki.paintings.config.ConfigurationHandler;
import subaraki.paintings.handler.EntityHandler;
import subaraki.paintings.handler.PatternLoader;
import subaraki.paintings.mod.proxy.CommonProxy;


@Mod(modid = MorePaintings.MODID, name = MorePaintings.NAME, version = MorePaintings.VERSION, dependencies = "after:PaintingSelGui")
public class MorePaintings {

    public static final String MODID = "morepaintings";
    public static final String VERSION = "$version";
    public static final String NAME = "Paintings++";

    @SidedProxy(serverSide = "subaraki.paintings.mod.proxy.CommonProxy", clientSide = "subaraki.paintings.mod.proxy.ClientProxy")
    public static CommonProxy proxy;
    public static Logger log;

    @Instance(MODID)
    public static MorePaintings INSTANCE;
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
    	INSTANCE = this;
    	
        log = event.getModLog();

        ModMetadata modMeta = event.getModMetadata();
        modMeta.authorList = Collections.singletonList("Subaraki");
        modMeta.autogenerated = false;
        modMeta.credits = "Subaraki";
        modMeta.description = "More Paintings! Check the config file for options.";
        modMeta.url = "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287285-/";
        
        ConfigurationHandler.instance.loadConfig(event.getSuggestedConfigurationFile());

        new PatternLoader();
        
        new EntityHandler();
        
        proxy.registerRenderInformation();
        
    }
}