package subaraki.paintings.mod;

import java.util.Collections;

import org.apache.logging.log4j.Logger;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import subaraki.paintings.config.ConfigurationHandler;
import subaraki.paintings.mod.entity.EntityHandler;
import subaraki.paintings.mod.network.NetworkHandler;
import subaraki.paintings.mod.network.PatternLoader;
import subaraki.paintings.mod.server.proxy.CommonProxy;


@Mod(modid = Paintings.MODID, name = Paintings.NAME, version = Paintings.VERSION, dependencies = "after:paintingselgui")
public class Paintings {

    public static final String MODID = "morepaintings";
    public static final String VERSION = "$version";
    public static final String NAME = "Paintings++";

    @SidedProxy(serverSide = "subaraki.paintings.mod.server.proxy.CommonProxy", clientSide = "subaraki.paintings.mod.client.proxy.ClientProxy")
    public static CommonProxy proxy;
    public static Logger log;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        log = event.getModLog();

        ModMetadata modMeta = event.getModMetadata();
        modMeta.authorList = Collections.singletonList("Subaraki");
        modMeta.autogenerated = false;
        modMeta.credits = "Subaraki";
        modMeta.description = "More Paintings! Check the config file for options.";
        modMeta.url = "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287285-/";

        ConfigurationHandler.instance.loadConfig(event.getSuggestedConfigurationFile());

        new EntityHandler();
        
        new PatternLoader();
        
        proxy.registerRenderInformation();
     
        new NetworkHandler();
    }
}